'use client';

import { useState, useEffect } from "react";
import { PDFDocument } from "pdf-lib";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import { useEditorStore } from "@/lib/store";
import { savePdf } from "@/lib/pdf-utils";
import { Download } from "lucide-react";

interface DownloadDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DownloadDialog({ open, onOpenChange }: DownloadDialogProps) {
  const { pdfFile } = useEditorStore();
  const [filename, setFilename] = useState("edited-document");
  const [format, setFormat] = useState<"pdf" | "png" | "jpeg">("pdf");
  const [isDownloading, setIsDownloading] = useState(false);

  // Metadata fields
  const [title, setTitle] = useState("");
  const [author, setAuthor] = useState("");
  const [subject, setSubject] = useState("");
  const [keywordsInput, setKeywordsInput] = useState("");

  const STORAGE_KEY = 'inkoro-download-metadata';

  // Prefill metadata when dialog opens (saved values take precedence)
  useEffect(() => {
    let cancelled = false;
    async function loadMetadata() {
      if (!open) return;

      try {
        // Load saved metadata from localStorage if present
        try {
          const raw = localStorage.getItem(STORAGE_KEY);
          if (raw) {
            const saved = JSON.parse(raw);
            setFilename(saved.filename ?? "edited-document");
            setTitle(saved.title ?? "");
            setAuthor(saved.author ?? "");
            setSubject(saved.subject ?? "");
            setKeywordsInput(saved.keywords ?? "");
            return;
          }
        } catch (e) {
          // ignore localStorage parse errors
        }

        if (!pdfFile) {
          setTitle("");
          setAuthor("");
          setSubject("");
          setKeywordsInput("");
          return;
        }

        const buffer = await pdfFile.arrayBuffer();
        const pdfDoc = await PDFDocument.load(buffer);

        if (cancelled) return;

        setTitle(pdfDoc.getTitle() ?? "");
        setAuthor(pdfDoc.getAuthor() ?? "");
        setSubject(pdfDoc.getSubject() ?? "");

        // pdf-lib stores keywords as a single string; convert to a comma separated list for the UI
        const rawKeywords = pdfDoc.getKeywords() ?? "";
        const kw = rawKeywords ? rawKeywords.split(/\s+/).join(', ') : '';
        setKeywordsInput(kw);
      } catch (err) {
        console.error('Failed to read PDF metadata', err);
      }
    }

    loadMetadata();
    return () => { cancelled = true; };
  }, [open, pdfFile]);

  const triggerDownload = (uint8: Uint8Array, name: string) => {
    const blob = new Blob([uint8.buffer as ArrayBuffer], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const sanitizedFilename = name?.trim()
      ? (name.toLowerCase().endsWith('.pdf') ? name.trim() : `${name.trim()}.pdf`)
      : 'edited_document.pdf';
    link.download = sanitizedFilename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const keywordsArray = keywordsInput.split(',').map((k) => k.trim()).filter(Boolean);

      // Persist current inputs so users don't have to retype next time
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify({
          filename,
          title,
          author,
          subject,
          keywords: keywordsInput
        }));
      } catch (e) { /* ignore storage errors */ }

      // Build PDF bytes with metadata
      const bytes = await savePdf({
        filename,
        title: title || undefined,
        author: author || undefined,
        subject: subject || undefined,
        keywords: keywordsArray.length ? keywordsArray : undefined,
        returnBytes: true,
      }) as Uint8Array | undefined;

      if (!bytes) throw new Error('Failed to generate PDF');

      // Trigger the download (generated bytes)
      triggerDownload(bytes, filename);
      onOpenChange(false);
    } catch (error) {
      console.error('Download failed:', error);
      try { const { toast } = await import('sonner'); toast('Download failed. See console for details.'); } catch {}
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <Download className="h-4 w-4 text-muted-foreground" />
            <DialogTitle>Download Document</DialogTitle>
          </div>
          <DialogDescription>
            Configure your export settings before downloading.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="filename">File Name</Label>
              <Input
                id="filename"
                value={filename}
                onChange={(e) => setFilename(e.target.value)}
                placeholder="edited-document"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="title">Title</Label>
              <Input id="title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Document title" />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="author">Author</Label>
              <Input id="author" value={author} onChange={(e) => setAuthor(e.target.value)} placeholder="Author name" />
            </div>

            <div className="space-y-2">
              <Label htmlFor="subject">Subject</Label>
              <Input id="subject" value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Subject" />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="keywords">Keywords</Label>
            <Input id="keywords" placeholder="Comma-separated keywords" value={keywordsInput} onChange={(e) => setKeywordsInput(e.target.value)} />
          </div>


        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isDownloading}>
            Cancel
          </Button>
          <Button onClick={handleDownload} disabled={isDownloading}>
            <Download className="h-4 w-4 mr-2" />
            {isDownloading ? "Downloading..." : "Download"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
